### ISSUE TITLE
unable to setup

### ISSUE THREAD

**Issue by KA1CM** [xltrail/git-xl#84]
Hi all, I've download and install Git XL, but can't set it up.

```
Microsoft Windows [Version 10.0.19045.3693]
(c) Microsoft Corporation. All rights reserved.

C:\Users\55tin>cd\

C:\>git xl install
'git' is not recognized as an internal or external command,
operable program or batch file.

C:\>
```

I believe the documentation is wrong, so I tried "git-xl install" with some improvement, but still not working.

```
C:\>git-xl install
Traceback (most recent call last):
  File "cli.py", line 283, in <module>
  File "cli.py", line 232, in execute
  File "cli.py", line 261, in install
  File "cli.py", line 54, in __init__
  File "cli.py", line 112, in get_global_gitconfig_dir
  File "cli.py", line 105, in execute
  File "subprocess.py", line 503, in run
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[16800] Failed to execute script 'cli' due to unhandled exception!

C:\>
```

**Comment by blacklee123** [comment]
you need install git first
